env:
  global:
    - LC_CTYPE=en_US.UTF-8
os: osx
language: c
matrix:
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - os: osx
  include:
    - osx_image: xcode8
      env:
        - XCODE_SDK=iphonesimulator
          XCODE_DESTINATION='platform=IOS Simulator,name=iPhone 6'

before_install:
    - export LANG=en_US.UTF-8
    - source ~/.rvm/scripts/rvm && rvm install ruby-2.2.4 && rvm use 2.2.4

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install bundler --no-rdoc --no-ri

script:
- set -o pipefail && xcodebuild test
  -project FlubberView.xcodeproj
  -scheme FlubberView
  -sdk ${XCODE_SDK}
  -destination "${XCODE_DESTINATION}"
  ONLY_ACTIVE_ARCH=NO | xcpretty
